version: "3.9"

services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
        
  backend:
    build: ./
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres_db
      DB_PORT: 5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./
        target: /app
    command: go run ./cmd/web/.

volumes:
  postgres_data:
